name: task_manager_app
description: "Task Manager App With GetX."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  line_icons: ^2.0.3
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  http: ^1.3.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  fluttertoast: ^8.2.11
  flutter_animate: ^4.5.2
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - images/
flutter_native_splash:
  android: true

  color: "#21BF73"
  image: "images/task_app-logo.png"


